spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/blog_test
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: true
    url: jdbc:mysql://localhost:3306/blog_test
    user: root
    password: password
    locations: classpath:db/migration