spring:
  application:
    name: blog-app

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/blog
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: false
    url: jdbc:mysql://localhost:3306/blog
    user: root
    password: password
    locations: classpath:db/migration
  servlet:
    multipart:
      max-file-size: 10MB

resilience4j:
  circuitbreaker:
    instances:
      gemini:
        registerHealthIndicator: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED


logging:
  level:
    root: debug
